### ISSUE TITLE
Does the library support the calculation of the pdf?

### ISSUE THREAD

**Issue by aWeinzierl** [StochasticEngineer/RandLib#13]
e.g. is it possible to calculate the pdf of a normal distribution (and store it in a vector)?

**Comment by astralord** [comment]
Sure it does. First you have to create random variable:
`NormalRand rv(0, 1);`
Then just call
`rv->ProbabilityDensityFunction(x, y);`
where x is a vector of input parameters and y is a vector to be filled with p.d.f. values.
