### ISSUE TITLE
Problems 

### ISSUE THREAD

**Issue by 1ncredibleM1nd** [StochasticEngineer/RandLib#14]
cloned this repository. 
But in Qt creator has problem : no viable constructor or deduction guide for deduction of template arguments of 'NormalRand'; 
Wrote code according your manual
 NormalRand X(0, 1);
    std::vector<double> data(1e6);
    X.Sample(data);

**Comment by astralord** [comment]
Unfortunately I wasn't able to reproduce this problem on my side. Could you try
`NormalRand<> X(0, 1)`
or
`NormalRand<double> X(0,1)`
instead?

If it doesn't fix problem for you, please revert to `master` branch, because `v1.1` is not a stable version yet.
