### ISSUE TITLE
Unitialized Variable in pdfForGeneralExponent() function from StableRand.cpp

### ISSUE THREAD

**Issue by nyoungbq** [StochasticEngineer/RandLib#17]
On [line 533](https://github.com/astralord/RandLib/blob/fff111968f5369b7ddaffac44289bbb26cc5c0f3/distributions/univariate/continuous/StableRand.cpp#L533) of `StableRand.cpp` the variable `theta0` is uninitialized when used 2 lines later.

**Comment by astralord** [comment]
Fixed in https://github.com/astralord/RandLib/commit/3c2698f61e7f0e55003d542b684bbc5c696d4910
