### ISSUE TITLE
Severe integer overflow occuring, leading to undefined behavior

### ISSUE THREAD

**Issue by nyoungbq** [StochasticEngineer/RandLib#19]
https://github.com/astralord/RandLib/blob/fff111968f5369b7ddaffac44289bbb26cc5c0f3/math/GammaMath.cpp#L34-L41

There is no way these values could be properly represented as the `long double` type you defined them as. See [this article from GeeksforGeeks](https://www.geeksforgeeks.org/how-to-avoid-integer-overflows-and-underflows-in-cpp/) for a simple reference on why this occurs and how this could be affecting your intended values. And [this StackOverflow post](https://stackoverflow.com/questions/17588419/when-a-float-variable-goes-out-of-the-float-limits-what-happens) is pertinent because of the type declaration.

**Comment by astralord** [comment]
Indeed, `long double` type limits were not taken into account here. Fixed in https://github.com/astralord/RandLib/commit/6536dadd6e532316848cade7e48f84fb40135767
